# Generated by Django 5.1.1 on 2024-09-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_questionsheet_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsheet',
            name='level',
        ),
    ]
