# Generated by Django 5.1.1 on 2024-09-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_remove_questionsheet_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsheet',
            name='level',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
        ),
    ]
