# Generated by Django 5.1.1 on 2024-09-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_questionsheet_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsheet',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
