# Generated by Django 4.1.13 on 2024-09-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_alter_questionsheet_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learn.questionsheet'),
        ),
        migrations.AlterField(
            model_name='questionsheet',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
