# Generated by Django 5.1.2 on 2025-02-13 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_alter_question_question_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsheet',
            name='attempted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionsheet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsheet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
