# Generated by Django 5.1.2 on 2025-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_questionsheet_attempted_count_questionsheet_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsheet',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
