# Generated by Django 5.1.2 on 2025-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_alter_questionsheet_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsheet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
