# Generated by Django 5.1.2 on 2025-02-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_remove_questionsheet_attempted_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsheet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='questionsheet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questionsheet',
            name='updated',
        ),
    ]
