# Generated by Django 5.1.2 on 2025-02-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_questionsheet_created_questionsheet_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsheet',
            name='updated',
        ),
    ]
