# Generated by Django 5.1.2 on 2025-02-18 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_remove_questionsheet_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsheet',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
