# Generated by Django 5.1.2 on 2025-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_questionsheet_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsheet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
